---
title: "Mínimos cuadrados en 2 etapas (laboratorio)"
author: "Econometría II"
format: 
  html:
    embed-resources: true
    theme: flatly
    css: custom-lab.css

date: last-modified
lang: es
toc-title: Contenido
toc: true
number-sections: false
number-depth: 2
format-links: false

editor: visual
---

## Datos

El archivo `mroz2.xlsx` contiene los salarios y características de una muestra de mujeres asalariadas en Estados Unidos en 1975. Son un subconjunto de los utilzados en Mroz (1987)[^1].

[^1]: Mroz (1987), T. A.: "The Sensitivity of an Empirical Model of Married Women’s Hours of Work to Economic and Statistical Assumptions,” *Econometrica* 55, 765-799.

-   `wage`: salario por hora, dólares.

-   `educ`: años en sistema educativo.

-   `exper`: años de experiencia laboral.

-   `fatheduc`: años en sistema educativo del padre.

-   `motheduc`: años en sistema educativo de la madre.

Para completar esta actividad se deben crear algunas variables adicionales:

-   `l_wage`: logaritmo del salario por hora.

## Instrucciones

1.  Estime por MCO la regresión del logaritmo del salario en función de los años de educación y experiencia laboral: $$\log(wage) = \beta_0 + \beta_1\,educ + \beta_2 exper + u.$$ {#eq-wage} Comente los resultados.

2.  Si la explicativa `educ` es endógena, MCO produce estimaciones inconsistentes. Se usarán como instrumentos los años de educación del padre y de la madre de cada trabajadora, `fatheduc` y `motheduc`. Estime la regresión de la primera etapa y contraste si los instrumentos son débiles.

3.  Use los residuos de la regresión de la primera etapa para contrastar la endogeneidad de `educ`.

4.  Estime los parámetros de la @eq-wage por mínimos cuadrados en 2 etapas, MC2E, usando `fatheduc` y `motheduc` como variables instrumentales. Compare los resultados con los obtenidos con MCO.

5.  Contraste la validez de las restricciones de sobreidentificación de la estimación por MC2E. ¿Qué se puede afirmar de la exogeneidad de los instrumentos?
